server:
  port: 8181
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /shici
spring:
  profiles:
        active: pro
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shici?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 3EMqN^C#*WKvCgSp
    driver-class: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 30000
    lettuce:
      pool:
        max-idle: 20
        min-idle: 20
        max-active: 100
        max-wait: 10
  #mybaits-plus配置，修改主键类型，mapper.xml、enums 别名等
  mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml
    typeAliasesPackage: com.pamc.api.entity
    global-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 0
      #驼峰下划线转换
      db-column-underline: true
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true



  logging:
    level:
      root : info
      org.apache.tomcat.util.net.NioEndpoint : warn
      com.jcn.mapper : debug
root:
  path: /zhenghongwei/project/shici/


